#!/bin/sh -e
# initramfs hook for saractl

. /usr/share/initramfs-tools/hook-functions

if [ -d /sys/kernel/security/sara/ ]; then
	copy_exec /usr/bin/base64 /bin
	copy_exec /bin/dd /bin
	copy_exec /bin/mktemp /bin
	/usr/bin/saractl config_to_file -F sh -o "${DESTDIR}/bin/sarainit" || true
	chmod +x "${DESTDIR}/bin/sarainit" || true
fi
