#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -e /bin/sarainit ]; then
	/bin/mount -t securityfs none /sys/kernel/security
	/bin/sarainit || true
fi
